server:
  port: 9001
spring:
  h2:
    console:
      enabled: true
  datasource:
    url: jdbc:h2:file:~/data/db_drones;AUTO_SERVER=true
    driver-class-name: org.h2.Driver
    username: drone
    password: drone
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect

springdoc:
  swagger-ui:
    path: /api-docs