-- liquibase formatted sql
-- changeset init:1

create table drone
(
    id               bigint generated by default as identity,
    battery_capacity integer,
    model            varchar(255) not null,
    serial_number    varchar(255),
    state            varchar(255) not null,
    weight_limit     integer,
    primary key (id)
);

create table drone_medicament
(
    drone_id      bigint not null,
    medicament_id bigint not null,
    primary key (drone_id, medicament_id)
);
create table medicament
(
    id        bigint generated by default as identity,
    code      varchar(255),
    image_url varchar(255),
    name      varchar(255),
    weight    integer,
    primary key (id)
);

alter table drone_medicament
    add constraint FKfoenv2efaqq0oss70l4u1fady foreign key (medicament_id) references medicament;
alter table drone_medicament
    add constraint FKcbbsa0bhcviiu2grnhie4a6h6 foreign key (drone_id) references drone;